language: python

install:
  pip install flake8

script:
  flake8

notifications:
  flowdock:
    secure: USj/UGy+pmW2lpYf/NMQCa4RvKE8c2r6KCSEZayzaRvTfMDs7OFBZ3pyZYYnrpIXePR2ufeMdUE7DnzId6aDcOXjbA2b4o6M1JLaXKJ8xAHcGeV9We4pg3g+kMx67Bxh4Sg74JjE76F2tvIWWL/6nViepccDjtAhCdDMGfCmpQFuKPEQnXxZH8LeLYdyPZWv8ZZOpB0U18hfXJPFjyio1oTZ6xilkPcQjOwc5K8XlxQfRyXbwRW82dQfB4kBL59iodl4BAHirBT/MR+2tYgq5yhcgfc46owfzyxtpEMjAbpE/qUg5eTv0j27nxN/h1DdOwL5eTn5cuwf5TPHoad42yi5FV+M13BYBCWzCOhNKCWRIlihtFioYKvQvMRzs3A8e+/cc0q/z5LiCWDRxcNic/5AdsIjn3wxb+lMxNTvmVNqu1OXDwG5AQX7z5xJA+4rbc3rbjsiISRF26O88uUWnK2ol2kiofmeFB8EjJ0LBBfkaZh/mG/EgM3xfwkanspLWIgOfr3ncPNlnAp3f1qoglCUb8tOdTKpoUMdfL7otYab5WYe50Gble2nZVy018yEGGTYCjFjxoKAUnXyNCIj9T3cUMZ7zLYTQ+AWiJiJeteNZGBCKUfg1aN2984rRfK6hyi3ZXPxBmr7wMsTIIeU4GkZ7ZyPPZCFTFfrZkMAoJM=
  flowdock:
    secure: c3H49xTR3YZHnG+1PfX8MDi67zFVnPi+2H4rJXs/1EvV7nFbyjJ7Nn898zNpF8CC/u+SVvQTSkSD+tA+3FQT/kjZd7LuCD/5Qy9GCOfK+gZVgj98485Rs0lODDvPOzRsfqibb1uqFahyAh5x/rmgH6cKLli5reN33XuAgXkeLqdj41JjxOb6ZYuFYG8kBmO2dsJpygk9QVhHd/PGuNEO5vltpL4P4d+xfmLcHJJskmLVviP1lVu3PtAqSiLcR6jZMiuNLYuW0WH5lJOV8pF4BEia7vPYkvCyFNTS6ApiKNYUSzg2onHNqpMaX1gQjI6pU/f/yFsp4oPEdi/UO6jzjm4ImoY0oCDdJJjJnnsMzw0mTwXjNQwhyrpK0fKbPN6ugh3ZEIdmQgeYdr0SEkHwLNCZxdtEhpcacpUQFyf8JuvNy/Ljrg7r1l/c3qTBjVN435cFiWDWYVKb61vhPBp//SOggMTKgj4Wova16Rr+XWDe5Ohp61DXYAosCjDBcW13vUtSDjNog5I+366DfQOwu0Yd8z/Dndr+q8h/dVctgitdlwMg/Py2Z94al+J5IsRtHuh9ZPuNvOTnsrumsxJmVNQshZMPY8zVQy9zj2OBRplp2RNlXSOs7H7mLrFOENWwraVrSuUNw3Kf0lhEGawPpAD3CPhtyzPcXFM0clv3ER4=
